Upgrade to 'go mod' from 'dep' and add pre-commit hooks
transcom/nom pull request #1
Opened 2019-06-26 22:39 UTC by chrisgilmerproj

I've migrated this repo to using `go mod`. After go1.12 was released they made it pretty clear that `go mod` was the future and vendoring was disappearing. So I've grabbed some of the code from transcom/mymove to migrate this repo as well.  You'll need to move your repo outside of your `$GOPATH` though, which is the one downside/upside to this change.

Additionally I've added pre-commit hooks that check golang and markdown files. They both showed up with a few easy-to-fix errors that I completed her as well.

To get `pre-commit` run `brew install pre-commit`. Then you can run `make ensure_pre_commit` to install everything. Then just run `pre-commit run -a` and you'll see all the checks run. There are more things I could add but I thought keeping it pretty minimal was fine for now.

I've also updated the `Makefile` a bit. Try building it now with `make clean bin/nom` or simply `make` if that's what you want to do.

2019-06-27 17:18 UTC, chrisgilmerproj commented
@jamesatheyDDS - sorry for the churn on this PR. I think it's in a good state now and would love for you to take a look.

2019-06-27 17:20 UTC, chrisgilmerproj commented on nom.go
> +		daysStarting31Dec1899, _ := strconv.Atoi(record[fields["Order Create/Modification Date"]])
This changed because it's an ineffectual assignment, meaning that `daysError` isn't checked or used before it's reassigned later in the code.

2019-08-22 19:10 UTC, chrisgilmerproj commented
As an update: I'm testing this change out now and it appears to work for me.

2019-08-22 19:30 UTC, mr337 requested changes
Precommit rules all look good
```
$ pre-commit run -a
Check for merge conflicts................................................Passed
Detect Private Key.......................................................Passed
Trim Trailing Whitespace.................................................Passed
golangci-lint............................................................Passed
markdownlint.............................................................Passed
```

Was able to compile with a simple make and pull in necessary deps.

Having an issue when running the makefile command
```
$ make ensure_pre_commit
make: *** No rule to make target '/usr/local/bin/pre-commit', needed by '.git/hooks/pre-commit'.  Stop.
```

2019-08-22 19:34 UTC, mr337 commented
Ah looking closer at the make file the `pre-commit` is different than what is installed. My `pre-commit` is installed different since installed with pup.
 ```
$ which pre-commit
/home/USER/.local/bin/pre-commit`
```

2019-08-22 20:05 UTC, chrisgilmerproj commented
> Ah looking closer at the make file the `pre-commit` is different than what is installed. My `pre-commit` is installed different since installed with pip.
> 
> ```
> $ which pre-commit
> /home/USER/.local/bin/pre-commit`
> ```

Generally we've found that the version in `pip` can diverge from `brew`. So a while ago we tried to move everyone off of `pip` to make sure it was the same in all environments. Up to you but I'd suggest moving.

2019-08-22 22:29 UTC, mr337 approved these changes
LGTM

2019-08-22 22:32 UTC, merged